import { useEffect, useState } from 'react';
import { api, label, money } from '../lib/api';
import Empty from './Empty';

export default function Challans({ user }) {
  const [challans, setChallans] = useState([]); const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]); const [showForm, setShowForm] = useState(false); const [selectedProduct, setSelectedProduct] = useState(''); const [customer, setCustomer] = useState(''); const [items, setItems] = useState([]); const [viewing, setViewing] = useState(null); const canEdit = ['admin', 'sales'].includes(user.role);
  const load = () => Promise.all([api('/challans').then(setChallans), api('/customers').then(setCustomers), api('/products').then(setProducts)]).catch(console.error);
  useEffect(load, []);
  const addItem = () => { const product = products.find((item) => item.id === selectedProduct); if (product && !items.some((item) => item.product_id === product.id)) setItems([...items, { product_id: product.id, product_name: product.name, product_sku: product.sku, unit_price: product.unit_price, quantity: 1 }]); setSelectedProduct(''); };
  const create = async (status) => { if (!customer || !items.length) return alert('Please select a customer and at least one product.'); try { await api('/challans', { method: 'POST', body: JSON.stringify({ customer_id: customer, items, status }) }); setItems([]); setCustomer(''); setShowForm(false); load(); } catch (error) { alert(error.message); } };
  const updateStatus = async (id, status) => { if (status === 'cancelled' && !window.confirm('Are you sure you want to cancel this draft challan?')) return; try { await api(`/challans/${id}/${status === 'confirmed' ? 'confirm' : 'cancel'}`, { method: 'POST' }); setViewing(null); load(); } catch (error) { alert(error.message); } };
  return <>
    <div className="page-heading"><div><div className="eyebrow">DISPATCH & ORDER OPERATIONS</div><h1>Sales Challans</h1><p className="muted">Prepare, confirm, and track every customer dispatch order.</p></div>{canEdit && <button className="button primary" onClick={() => setShowForm(true)}>+ New challan</button>}</div>
    {showForm && <div className="panel form-panel"><div className="form-header"><h3>Create Sales Challan</h3><button className="icon-button" onClick={() => setShowForm(false)}>×</button></div><label>Customer *<select value={customer} onChange={(e) => setCustomer(e.target.value)}><option value="">Select customer</option>{customers.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.business_name || 'Personal'} ({label(item.customer_type)})</option>)}</select></label><div className="add-product-row"><select value={selectedProduct} onChange={(e) => setSelectedProduct(e.target.value)}><option value="">Add products</option>{products.map((item) => <option value={item.id} key={item.id}>{item.name} · {money(item.unit_price)} (Available: {item.current_stock})</option>)}</select><button className="button" type="button" onClick={addItem}>+ Add Line Item</button></div>{items.map((item, index) => <div className="line-item" key={item.product_id}><div><b>{item.product_name}</b><span className="subtext">{money(item.unit_price)} each</span></div><div><span>Qty:</span><input type="number" min="1" value={item.quantity} onChange={(e) => setItems(items.map((row, rowIndex) => rowIndex === index ? { ...row, quantity: Number(e.target.value) } : row))} /></div><button type="button" onClick={() => setItems(items.filter((row) => row.product_id !== item.product_id))}>×</button></div>)}<div className="form-actions"><button className="button" type="button" onClick={() => create('draft')}>Save as Draft</button><button className="button primary" type="button" onClick={() => create('confirmed')}>Save & Confirm Dispatch</button></div></div>}
    <div className="panel table-panel"><table><thead><tr><th>Challan No</th><th>Customer</th><th>Items</th><th>Total Qty</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{challans.map((item) => <tr key={item.id}><td><code>{item.challan_number}</code></td><td><b>{item.customers?.name || '—'}</b><span className="subtext">{item.customers?.business_name}</span></td><td>{item.challan_items?.length || 0} products</td><td><b>{item.total_quantity}</b></td><td><span className={`status ${item.status}`}>{label(item.status)}</span></td><td>{new Date(item.created_at).toLocaleDateString('en-IN')}</td><td><div className="table-actions"><button className="text-button" onClick={() => setViewing(item)}>View</button>{item.status === 'draft' && canEdit && <><button className="text-button" onClick={() => updateStatus(item.id, 'confirmed')}>Confirm</button><button className="text-button danger" onClick={() => updateStatus(item.id, 'cancelled')}>Cancel</button></>}</div></td></tr>)}</tbody></table>{!challans.length && <Empty text="No challans yet" />}</div>
    {viewing && <div className="modal-backdrop"><div className="modal"><div className="form-header"><div><div className="eyebrow">SALES CHALLAN</div><h2>{viewing.challan_number}</h2></div><button className="icon-button" onClick={() => setViewing(null)}>×</button></div><div className="detail-grid"><div><span>Customer</span><b>{viewing.customers?.name || '—'}</b></div><div><span>Business</span><b>{viewing.customers?.business_name || '—'}</b></div><div><span>Status</span><b className={`status ${viewing.status}`}>{label(viewing.status)}</b></div><div><span>Total Quantity</span><b>{viewing.total_quantity} units</b></div></div><hr /><h3>Product Snapshot Items</h3><table className="items-table"><thead><tr><th>Product</th><th>SKU</th><th>Unit Price</th><th>Quantity</th><th>Subtotal</th></tr></thead><tbody>{(viewing.challan_items || []).map((line) => <tr key={line.id}><td><b>{line.product_name}</b></td><td><code>{line.product_sku}</code></td><td>{money(line.unit_price)}</td><td><b>{line.quantity}</b></td><td>{money((line.unit_price || 0) * (line.quantity || 1))}</td></tr>)}</tbody></table><div className="form-actions">{viewing.status === 'draft' && canEdit && <><button className="button danger" onClick={() => updateStatus(viewing.id, 'cancelled')}>Cancel Challan</button><button className="button primary" onClick={() => updateStatus(viewing.id, 'confirmed')}>Confirm Dispatch</button></>}<button className="button" onClick={() => setViewing(null)}>Close</button></div></div></div>}
  </>;
}
