import { useEffect, useState } from 'react';
import { api, money } from '../lib/api';
import Empty from './Empty';

export default function Inventory({ user }) {
  const [tab, setTab] = useState('products');
  const [products, setProducts] = useState([]);
  const [movements, setMovements] = useState([]);
  const [search, setSearch] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState(null);
  const [adjustTarget, setAdjustTarget] = useState(null);
  const canEdit = ['admin', 'warehouse'].includes(user.role);
  const loadProducts = () => api(`/products?search=${encodeURIComponent(search)}`).then(setProducts).catch(console.error);
  const loadMovements = () => api('/stock-movements').then(setMovements).catch(console.error);
  useEffect(() => { tab === 'products' ? loadProducts() : loadMovements(); }, [search, tab]);
  const save = async (event) => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.target)); await api(editing ? `/products/${editing.id}` : '/products', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(body) }); setEditing(null); setShowForm(false); loadProducts(); };
  const adjust = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); await api(`/products/${data.product_id}/movements`, { method: 'POST', body: JSON.stringify({ movement_type: data.movement_type, quantity_change: Number(data.quantity_change), reason: data.reason }) }); setAdjustTarget(null); loadProducts(); if (tab === 'movements') loadMovements(); };
  return <>
    <div className="page-heading"><div><div className="eyebrow">WAREHOUSE & STOCK CONTROL</div><h1>Inventory</h1><p className="muted">Track catalog products, real-time stock levels, and audit logs.</p></div>{canEdit && <div className="header-actions"><button className="button" onClick={() => setAdjustTarget({})}>⇄ Adjust stock</button><button className="button primary" onClick={() => { setEditing(null); setShowForm(true); }}>+ Add product</button></div>}</div>
    <div className="tabs"><button className={tab === 'products' ? 'tab-button active' : 'tab-button'} onClick={() => setTab('products')}>Product Catalog ({products.length})</button><button className={tab === 'movements' ? 'tab-button active' : 'tab-button'} onClick={() => setTab('movements')}>Stock Movement Log</button></div>
    {tab === 'products' && <><div className="toolbar"><div className="search">⌕<input placeholder="Search product, SKU, category" value={search} onChange={(e) => setSearch(e.target.value)} /></div><span className="result-count">{products.length} products</span></div>{(showForm || editing) && <div className="panel form-panel"><form onSubmit={save}><div className="form-header"><h3>{editing ? `Edit Product: ${editing.name}` : 'New product'}</h3><button type="button" className="icon-button" onClick={() => { setShowForm(false); setEditing(null); }}>×</button></div><div className="form-grid"><label>Product name *<input name="name" required defaultValue={editing?.name || ''} /></label><label>SKU / Code *<input name="sku" required defaultValue={editing?.sku || ''} /></label><label>Category<input name="category" defaultValue={editing?.category || ''} /></label><label>Unit price (₹)<input name="unit_price" type="number" min="0" step="0.01" required defaultValue={editing?.unit_price || ''} /></label>{!editing && <label>Opening stock<input name="opening_stock" type="number" min="0" defaultValue="0" /></label>}<label>Minimum alert quantity<input name="min_stock_alert" type="number" min="0" defaultValue={editing?.min_stock_alert || '10'} /></label><label className="wide">Warehouse / location<input name="location" defaultValue={editing?.location || 'Warehouse A'} /></label></div><div className="form-actions"><button type="button" className="button" onClick={() => { setShowForm(false); setEditing(null); }}>Cancel</button><button className="button primary">{editing ? 'Update product' : 'Save product'}</button></div></form></div>}<div className="panel table-panel"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Price</th><th>Current Stock</th><th>Location</th><th>Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><b>{product.name}</b></td><td><code>{product.sku}</code></td><td>{product.category || '—'}</td><td>{money(product.unit_price)}</td><td><span className={product.current_stock <= product.min_stock_alert ? 'stock low' : 'stock'}>{product.current_stock} <small>units</small></span></td><td>{product.location || '—'}</td><td>{canEdit && <div className="table-actions"><button className="text-button" onClick={() => setAdjustTarget(product)}>Adjust</button><button className="text-button" onClick={() => { setEditing(product); setShowForm(false); }}>Edit</button></div>}</td></tr>)}</tbody></table>{!products.length && <Empty text="No products yet" />}</div></>}
    {tab === 'movements' && <div className="panel table-panel"><table><thead><tr><th>Product</th><th>Movement</th><th>Quantity</th><th>Reason</th><th>Logged By</th><th>Timestamp</th></tr></thead><tbody>{movements.map((item) => <tr key={item.id}><td><b>{item.products?.name || 'Product'}</b></td><td><span className={`movement-badge ${item.movement_type.toLowerCase()}`}>{item.movement_type}</span></td><td>{item.quantity_change}</td><td>{item.reason || '—'}</td><td>{item.users?.name || 'System / Admin'}</td><td>{new Date(item.created_at).toLocaleString('en-IN')}</td></tr>)}</tbody></table>{!movements.length && <Empty text="No stock movements recorded yet" />}</div>}
    {adjustTarget && <div className="modal-backdrop"><div className="modal"><div className="form-header"><h3>Record Stock Movement</h3><button className="icon-button" onClick={() => setAdjustTarget(null)}>×</button></div><form onSubmit={adjust}><label>Product *<select name="product_id" required defaultValue={adjustTarget.id || ''}><option value="">Select a product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name} ({product.sku})</option>)}</select></label><div className="form-grid"><label>Movement Type<select name="movement_type" defaultValue="IN"><option value="IN">IN</option><option value="OUT">OUT</option></select></label><label>Quantity Changed<input name="quantity_change" type="number" min="1" required defaultValue="1" /></label></div><label>Reason / Note *<input name="reason" required /></label><div className="form-actions"><button type="button" className="button" onClick={() => setAdjustTarget(null)}>Cancel</button><button className="button primary">Confirm Movement</button></div></form></div></div>}
  </>;
}
